apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: teamk8
  labels:
    app: mongo
spec:
  type:  ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongo
